### ISSUE TITLE
Rookgaard NPCs

### ISSUE THREAD

**Issue by wizardlink** [Hydractify/forgottenserver#1]
We need to implement all the NPCs located in Rookgaard, a sum of [25 NPCs](https://tibia.fandom.com/wiki/Rookgaard#NPCs) exist in the town.

All of these NPCs were implemented in [`orts/server`](https://github.com/orts/server) but we have to update those files to the latest TFS version. Some of these NPCs also have flawed conversations, either lacking on dialog or just straight up no code for some dialog.

Here is the list of NPCs: https://tibia.fandom.com/wiki/Rookgaard#NPCs

**Comment by CaptMU167** [comment]
I am working on this NPC: https://tibia.fandom.com/wiki/Amber

**Comment by wizardlink** [comment]
All NPCs XML files from Rookgaard have been added. They are all working, meaning, all NPC do spawn.

Reminder that they work because the `script` attribute of the `npc` tag is not present. Whenever anyone decides to make an NPC, they have to add that attribute and point at the right file name. You guys can use `Al Dee` as a base reference for NPCs.

Another thing to consider is that [`orts/server`](https://github.com/orts/server) doesn't uses the `MESSAGE_GREET` and related constants in the `*.xml` file of the NPC. So those have to be ported from the NPC's script to it's `XML`. Again, you can use `Al Dee` for reference.

**Comment by wizardlink** [comment]
Alright, with that said, I will be working on [The Beginning Quest](https://tibia.fandom.com/wiki/The_Beginning_Quest) now. That's the first thing all players will have to go through so they can reach Rookgaard. So while you guys work on the city, I'll work on the island below it.

**Comment by wizardlink** [comment]
Ok, so I have added every single NPC to the game in the commit a83e8861f5958b40a5b36cbde4f8b6a60b03ff62. With that said, none of the NPCs I added were tested.

I will move on and start adding other parts of the datapack in a bulk, while I do so, I want you @CaptMU167 to start testing all NPCs in Rookgaard while I do so, of course, after you finish Amber.

**Comment by wizardlink** [comment]
Closing issue due to the centralization of Rookgaard implementations being covered in issue #10.
